rosdistro: 'noetic

  '
roslaunch:
  uris:
    host_ubuntu__36819: http://ubuntu:36819/
rosversion: '1.16.0

  '
run_id: 5a8642c8-0e9d-11ee-9951-f13801378d4b
turtlesim:
  background_b: 255
  background_g: 86
  background_r: 150
